---
cluster_name: Kubernetes Cluster
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 172.10.10.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 4
    memory: 4096
  workers:
    count: 1
    cpu: 2
    memory: 2048
software:
  box: bento/ubuntu-22.04
  calico: 3.26.0
  kubernetes: 1.28.0-*

  os: xUbuntu_22.04
